
services:
  - type: web
    name: workwear-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_real_bot_token_here
