services:
  - type: web
    name: workwear-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y python3.12 python3.12-venv
      python3.12 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: ". venv/bin/activate && python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_real_bot_token_here
