services:
  - type: web
    name: workwear-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3.12 -
      pip install -r requirements.txt
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_real_bot_token_here
